// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGxKbwxlRJm2Umn3-E9p6VP_dSz_5UuNs',
    appId: '1:776183833321:web:5a9452c73368387b42c678',
    messagingSenderId: '776183833321',
    projectId: 'ai-assistant-33cbf',
    authDomain: 'ai-assistant-33cbf.firebaseapp.com',
    storageBucket: 'ai-assistant-33cbf.appspot.com',
    measurementId: 'G-2WWNHRGM4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ0QZv5QJFB-2FAP9cFurFWN_-TipKBAQ',
    appId: '1:776183833321:android:7b675fc22ba480ac42c678',
    messagingSenderId: '776183833321',
    projectId: 'ai-assistant-33cbf',
    storageBucket: 'ai-assistant-33cbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC54UBrFT0JQK8J1wg4Ms7Yw68926dq1S0',
    appId: '1:776183833321:ios:2d76a27d1cf26e1c42c678',
    messagingSenderId: '776183833321',
    projectId: 'ai-assistant-33cbf',
    storageBucket: 'ai-assistant-33cbf.appspot.com',
    iosBundleId: 'com.example.aiAssis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC54UBrFT0JQK8J1wg4Ms7Yw68926dq1S0',
    appId: '1:776183833321:ios:2d76a27d1cf26e1c42c678',
    messagingSenderId: '776183833321',
    projectId: 'ai-assistant-33cbf',
    storageBucket: 'ai-assistant-33cbf.appspot.com',
    iosBundleId: 'com.example.aiAssis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGxKbwxlRJm2Umn3-E9p6VP_dSz_5UuNs',
    appId: '1:776183833321:web:e9f934e928040f1d42c678',
    messagingSenderId: '776183833321',
    projectId: 'ai-assistant-33cbf',
    authDomain: 'ai-assistant-33cbf.firebaseapp.com',
    storageBucket: 'ai-assistant-33cbf.appspot.com',
    measurementId: 'G-9N4Z7QNQVX',
  );
}
